# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: backend
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    profiles:
      - ''
      - prod
  elasticsearch:
    extends:
      file: ./elasticsearch.yml
      service: elasticsearch
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
